#!/usr/bin/env bash
# Generate LVGL C Voice AI Japanese fallback font used by firmware.
#
# Run from the project root:
#   firmware/tools/gen_voice_font.sh
#
# Requirements:
#   - lv_font_conv (via npx or in PATH)
#   - python3 in PATH
#   - Zfull-GB.ttf at backend/assets/fonts/vector/Zfull-GB.ttf
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

readonly OUT_DIR="firmware/main/resources/fonts"
readonly DEFAULT_ZFULL_TTF="backend/assets/fonts/vector/Zfull-GB.ttf"
ZFULL_TTF="${ZFULL_TTF:-$DEFAULT_ZFULL_TTF}"

cd "$REPO_ROOT"

if [ ! -f "$ZFULL_TTF" ]; then
    echo "error: missing source font: $ZFULL_TTF" >&2
    exit 1
fi

mkdir -p "$OUT_DIR"

# Common Japanese Kanji strategy:
# Covers Kyōiku (grades 1-6) and conversational Japanese Kanji not present in GB2312,
# plus core Japanese conversational keywords (今日何曜日日本語).
# Characters already present in GB2312 fallback font (Zfull_16) are automatically
# resolved via the .fallback pointer.
COMMON_KANJI_SYMBOLS="$(python3 - <<'PY'
import sys

# Kyōiku Kanji not covered by GB2312 plus core conversational Japanese words
MISSING_KYOIKU_AND_COMMON = (
    "今日何曜日日本語"
    "伝価係俵倉個側備傷働僕億優児円冊処別則創劇労効動務勝勢協単厳員問営団囲図園圧報場塩増売奮姉婦孫"
    "実宮対専導層島巣巻師帯帳幹幾庁庫張強従復徳応悪愛態慣憲戦戸拝拡挙捨採揮損敗敵時晩書東査栄桜検業"
    "極構様標権樹橋機歩歯歴殺毎気氷決沖済減測湯準漁漢潔災無焼熱現産畑異発県確種穀窓競筆節築簡紀約紅"
    "納純紙級細終組経結給統絵絶絹続綺綿総緑線縄縦縮績義習聖聞職脈脳臓臨興舎葉蔵薬衆術衛裏補製複見規"
    "視覚覧親観計討訓訪設許訳証評詞試詩話誌認誕語誠誤説読誰課調談論諸講謝識議護豊貝負財貧貨責貯貴買"
    "貸費貿賀賃資賑賛賞質車軍転軽輸連週進遊運過達遠適選遺郵郷針鉄鉱銀銅銭鋼録鏡門閉開関閣陸険陽隊階"
    "際雑難雲電曇頂順預領頭題額願風飛飯飲飼館馬駅験魚鳥鳴麗黒"
)

unique_kanji = "".join(sorted(set(MISSING_KYOIKU_AND_COMMON)))
sys.stdout.write(unique_kanji)
PY
)"

postprocess_font() {
    local file="$1"
    python3 - "$file" "$ZFULL_TTF" <<'PY'
import os
import sys
from pathlib import Path

path = Path(sys.argv[1])
ttf_path = sys.argv[2]
text = path.read_text(encoding="utf-8")

old_inc = (
    "#ifdef LV_LVGL_H_INCLUDE_SIMPLE\n"
    "#include \"lvgl.h\"\n"
    "#else\n"
    "#include \"lvgl/lvgl.h\"\n"
    "#endif"
)
text = text.replace(old_inc, '#include "lvgl.h"')

lines = []
for line in text.splitlines():
    if line.startswith(" * Opts: "):
        lines.extend(
            [
                " * Generated by: firmware/tools/gen_voice_font.sh",
                f" * Source font: {ttf_path}",
                " * Fallback: Zfull_16",
                " * Coverage: ASCII (0x20-0x7F), Japanese punctuation (0x3000-0x303F),",
                " *           Hiragana (0x3040-0x309F), Katakana (0x30A0-0x30FF),",
                " *           Fullwidth forms (0xFF01-0xFF60), Common Japanese Kanji.",
                " * License: Compatible with project font assets (Zfull-GB).",
            ]
        )
    else:
        lines.append(line)

path.write_text('\n'.join(lines).rstrip('\n') + '\n', encoding='utf-8')
PY
}

echo "Generating $OUT_DIR/voice_font_16.c..."

LV_FONT_CONV_BIN="lv_font_conv"
if ! command -v "$LV_FONT_CONV_BIN" >/dev/null 2>&1; then
    LV_FONT_CONV_BIN="npx lv_font_conv"
fi

$LV_FONT_CONV_BIN     --no-compress     --bpp 1     --size 16     --font "$ZFULL_TTF"     --autohint-off     -r 0x20-0x7F,0x3000-0x303F,0x3040-0x309F,0x30A0-0x30FF,0xFF01-0xFF60     --symbols "$COMMON_KANJI_SYMBOLS"     --format lvgl     --output "$OUT_DIR/voice_font_16.c"     --lv-font-name Voice_Font_16     --lv-fallback Zfull_16

postprocess_font "$OUT_DIR/voice_font_16.c"

echo "done: $OUT_DIR/voice_font_16.c"
